name: Deploy Docs

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: setup and build
        run: |
          git clone https://github.com/n8n-io/n8n
          cd n8n
          git checkout N8N-5602-form-inputs-updates
          cd packages/design-system/
          npm install
          npm run build:storybook
          cd storybook-static
          git init
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add -A
          git commit -m "Deploy" -a
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: 'n8n/packages/design-system/storybook-static'
